name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
  pull_request:

jobs:
  TOX:
    name: "Run setup and tox."
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Run installs.
        run: pip install -e .[test]
      - name: Run Tox
        run: tox
      - name: Run Mypy
        run: mypy

      # - name: Run setup of PySIAAlarm
      #   run: python setup.py develop
      # - name: Test with pytest
      #   run: python setup.py test
